/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.model.ResourceTypePermission;
import com.liferay.portal.kernel.service.ResourceTypePermissionLocalServiceUtil;

/**
 * The extended model base implementation for the ResourceTypePermission service. Represents a row in the &quot;ResourceTypePermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceTypePermissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceTypePermissionImpl
 * @see ResourceTypePermission
 * @deprecated As of Judson (7.1.x), with no direct replacement
 * @generated
 */
@Deprecated
public abstract class ResourceTypePermissionBaseImpl
	extends ResourceTypePermissionModelImpl implements ResourceTypePermission {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resource type permission model instance should use the <code>ResourceTypePermission</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ResourceTypePermissionLocalServiceUtil.addResourceTypePermission(
				this);
		}
		else {
			ResourceTypePermissionLocalServiceUtil.updateResourceTypePermission(
				this);
		}
	}

}