dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:portal-instances:portal-instances-api")
	compileOnly project(":apps:text-localizer:text-localizer-address-api")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-phloem:osb-koroneiki-phloem-rest-api")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-phytohormone:osb-koroneiki-phytohormone-api")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-root:osb-koroneiki-root-api")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-scion:osb-koroneiki-scion-api")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-taproot:osb-koroneiki-taproot-api")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-trunk:osb-koroneiki-trunk-api")
}