buildService {
	apiDir = "../osb-provisioning-api/src/main/java"
	databaseNameMaxLength = 64
}

dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:petra:petra-content")
	compileOnly project(":apps:portal-search:portal-search-api")
	compileOnly project(":apps:portal-search:portal-search-spi")
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:portal:portal-upgrade-api")
	compileOnly project(":apps:static:osgi:osgi-util")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:osb:osb-koroneiki:osb-koroneiki-phloem:osb-koroneiki-phloem-rest-client")
	compileOnly project(":dxp:apps:osb:osb-provisioning:osb-provisioning-api")
	compileOnly project(":dxp:apps:osb:osb-provisioning:osb-provisioning-koroneiki:osb-provisioning-koroneiki-api")
	compileOnly project(":dxp:apps:osb:osb-provisioning:osb-provisioning-koroneiki:osb-provisioning-koroneiki-web-service-api")
}