##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/tests/Kaleodesigner.testcase